### PR TITLE
Proper 0.8 compendium refactor + Drop workflow refactor

### LINKED ISSUE #210: [BUG] Can't edit HP on tokens
**Describe the bug**
Token resources use the derived HP values, which means we can't edit them from the token directly

**To Reproduce**
image

**Platform (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, firefox]
 - Foundry version 0.8.6
 - Lancer system version 0.9.3

### LINKED ISSUE #213: [BUG] [0.9.3] Adding status effects to a token sets its HP box to zero
**Describe the bug**
When adding status effects to a token, the value in the HP box drops to zero.

**To Reproduce**
1. Create a token.
2. Click on it.
3. Add a status effect using the pop-up interface.

**Expected behavior**
Adding status effects should not affect the value in the HP box.

**Screenshots**
Status effects 1
Status effects 2

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.8.6
 - Lancer system version 0.9.3

**Discord contact info**
Vex#1075

### LINKED ISSUE #217: [BUG] [0.9.3] Can't add additional systems to NPCs
**Describe the bug**
Dragging and dropping optional systems onto NPCs no longer seems to work. This seems to affect both the master character sheet of an NPC and its unlinked token duplicates.

**To Reproduce**
1. Create a new NPC.
2. Drag a class onto the NPC's character sheet (for this test, I used a Bombard).
3. Attempt to drag and drop optional systems from the same class onto the NPC's character sheet.
4. Attempt to drag and drop optional or core systems from a different class onto the NPC's character sheet.

**Expected behavior**
You should be able to add optional systems to NPCs.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Foundry version 0.8.6
 - Lancer system version 0.9.3

**Discord contact info**
Vex#1075

### LINKED ISSUE #219: [BUG] Importing Item from Compendium wipes string data
**Describe the bug**
After import:
image

**To Reproduce**
Import an item

**Platform (please complete the following information):**
 - Foundry version 0.8.6
 - Lancer system version 0.9.3

### LINKED ISSUE #221: [BUG] Non-Veteran Templates don't add Structure or Stress
**Describe the bug**
Adding the Elite or Ultra templates doesn't add extra Struct/Stress to an NPC. Veteran does, so it's not a problem across the board.

**To Reproduce**
1. Create NPC
2. Add Elite or Ultra Template
3. Observe Structure remaining at 1/1.

**Expected behavior**
Automatic increment of Structure.

**Platform (please complete the following information):**
 - OS: Win10
 - Foundry version 0.8.6
 - Lancer system version 0.9.3

**Discord contact info**
It's Vexx. No, not that one.

### LINKED ISSUE #224: [BUG] Calling destroy_entry on item embedded in token doesn't work well
**Describe the bug**
Things that trigger destroy_entry on a token actor result in an error and inconsistent behavior.

**To Reproduce**
1. Create NPC with class
2. Create token from NPC
3. Attempt to delete class
4. Observe that the class didn't fully delete

**Expected behavior**
Should be handled seamlessly

**Screenshots**
image
image

**Platform (please complete the following information):**
 - Foundry version 0.8.6
 - Lancer system version 0.9.3

### PR DESCRIPTION
**Pull request by whitespine**
NOTE: WILL BREAK EXISTING WORLDS
WHATS PRIMARILY CHANGED:
 - Registries are named diffferent
 - Registries are generally more robust in how they import stuff
 - Compendium LCP import got refactored to be more straightforward + good
 - Bunch of token inventory/editing fixes
 - Compendium import fixed
 - Manufacturer linking fixed
 - Licenses repopulate/scan on demand now
 - Shit's way faster now 😎 
 - Drop workflow now gives live MM entries, which makes a lot of things a lot simpler down the road

~~WHATS STILL MISSING _Don't get mad at me yet >:(_:~~
 ~~- I gotta do some basic translation between "old-style" (read: 0.9.x beta release) refs to new style. This will fix it for .9.* worlds made earlier. I'm not going to go super hard on this, but no sense nuking their setups~~

Resolves the following:
Fixes #219 
Fixes #213 
Fixes #210 
Fixes #217 
Fixes #224 
Fixes #221 
Fixes whitespine constantly whining about the drop code being extremely cursed

### CODE REVIEW

File: src/module/item/npc-class-sheet.ts [hunk 1]
```diff
@@ -85,138 +85,6 @@ export class LancerNPCClassSheet extends LancerItemSheet<EntryType.NPC_CLASS> {
     return data.map(x => parseFloat(x));
```
Comment (Grygon) [inline src/module/item/npc-class-sheet.ts:85]: Removed ability to add features to classes--should re-add for #110

Comment (whitespine) [reply src/module/item/npc-class-sheet.ts:85]: Oh, right. You still can, I suppose it's not as intuitive anymore though

Comment (Grygon) [reply src/module/item/npc-class-sheet.ts:85]: How can you? Haven't been able to figure it out... is my world maybe just broken for dragdrop?

Comment (whitespine) [reply src/module/item/npc-class-sheet.ts:85]: Drag the portrait of the feature, which acts as a regret draggable and thus has the proper logic to reveal the drop locations. I've ideas for how to solve this issue but need to avoid orphaned listeners

Comment (Grygon) [reply src/module/item/npc-class-sheet.ts:85]: Ah... yeah that's weird, no easy way to tie that into the compendiums I'm guessing based on current setup? That's how it'll be done 99% of the time so that's the one we'll need to have work
